_wandb:
    value:
        cli_version: 0.21.0
        e:
            k2x1hb3wyfzylxp9nzuygdh4fh4u9dzf:
                args:
                    - --seed
                    - "42"
                    - --pretrained_model_name_or_path
                    - /root/autodl-tmp/.cache/hub/models--black-forest-labs--FLUX.1-dev/snapshots/3de623fc3c33e44ffbe2bad470d0f45bccf2eb21
                    - --vae_model_path
                    - /root/autodl-tmp/.cache/hub/models--black-forest-labs--FLUX.1-dev/snapshots/3de623fc3c33e44ffbe2bad470d0f45bccf2eb21
                    - --cache_dir
                    - /root/autodl-tmp/.cache/hub
                    - --data_json_path
                    - /root/autodl-tmp/DiffusionGRPO/data/rl_embeddings/txt2img.json
                    - --gradient_checkpointing
                    - --train_batch_size
                    - "2"
                    - --num_latent_t
                    - "1"
                    - --sp_size
                    - "1"
                    - --train_sp_batch_size
                    - "2"
                    - --dataloader_num_workers
                    - "4"
                    - --gradient_accumulation_steps
                    - "12"
                    - --max_train_steps
                    - "300"
                    - --learning_rate
                    - "1e-5"
                    - --mixed_precision
                    - bf16
                    - --checkpointing_steps
                    - "40"
                    - --allow_tf32
                    - --cfg
                    - "0.0"
                    - --output_dir
                    - /root/autodl-tmp/DiffusionGRPO/data/outputs/grpo
                    - --h
                    - "1024"
                    - --w
                    - "1024"
                    - --t
                    - "1"
                    - --sampling_steps
                    - "20"
                    - --eta
                    - "0.3"
                    - --lr_warmup_steps
                    - "0"
                    - --sampler_seed
                    - "1223627"
                    - --max_grad_norm
                    - "1.0"
                    - --weight_decay
                    - "0.0001"
                    - --use_hpsv2
                    - --num_generations
                    - "12"
                    - --shift
                    - "3"
                    - --use_group
                    - --ignore_last
                    - --timestep_fraction
                    - "0.6"
                    - --init_same_noise
                    - --clip_range
                    - "1e-4"
                    - --adv_clip_max
                    - "5.0"
                    - --use_aesthetics_reward
                codePath: src/train_grpo_flux.py
                codePathLocal: src/train_grpo_flux.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "27158597632"
                email: qianz@zju.edu.cn
                executable: /root/miniconda3/envs/aigc_rl/bin/python3.10
                git:
                    commit: cafe04603f787af48f7a7c59b1036e1df247f93b
                    remote: https://github.com/TaylorJocelyn/DiffusionGRPO.git
                gpu: NVIDIA H20
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 9984
                      memoryTotal: "102625181696"
                      name: NVIDIA H20
                      uuid: GPU-691c30f8-f381-3b4c-8f92-543ebb3a8571
                    - architecture: Hopper
                      cudaCores: 9984
                      memoryTotal: "102625181696"
                      name: NVIDIA H20
                      uuid: GPU-ac13be6b-ec55-6871-6559-566cd8b049b2
                    - architecture: Hopper
                      cudaCores: 9984
                      memoryTotal: "102625181696"
                      name: NVIDIA H20
                      uuid: GPU-30e0a551-00c1-297b-639d-d547d7bb6e3a
                host: autodl-container-c22545b252-a59d2c76
                memory:
                    total: "1330811752448"
                os: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
                program: /root/autodl-tmp/DiffusionGRPO/src/train_grpo_flux.py
                python: CPython 3.10.18
                root: /root/autodl-tmp/DiffusionGRPO
                startedAt: "2025-08-23T22:50:52.466151Z"
                writerId: k2x1hb3wyfzylxp9nzuygdh4fh4u9dzf
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 51
                - 63
                - 71
                - 83
                - 95
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 51
                - 63
                - 71
                - 83
                - 95
                - 98
                - 105
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.50.0
            "12": 0.21.0
            "13": linux-x86_64
adv_clip_max:
    value: 5
allow_tf32:
    value: true
cache_dir:
    value: /root/autodl-tmp/.cache/hub
cfg:
    value: 0
checkpointing_steps:
    value: 40
clip_range:
    value: 0.0001
data_json_path:
    value: /root/autodl-tmp/DiffusionGRPO/data/rl_embeddings/txt2img.json
dataloader_num_workers:
    value: 4
dit_model_name_or_path:
    value: null
ema_decay:
    value: 0.995
ema_start_step:
    value: 0
eta:
    value: 0.3
fsdp_sharding_startegy:
    value: full
gradient_accumulation_steps:
    value: 12
gradient_checkpointing:
    value: true
h:
    value: 1024
ignore_last:
    value: true
init_same_noise:
    value: true
learning_rate:
    value: 1e-05
log_dir:
    value: runs
logging_dir:
    value: logs
loss_coef:
    value: 1
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant_with_warmup
lr_warmup_steps:
    value: 0
master_weight_type:
    value: fp32
max_grad_norm:
    value: 1
max_train_steps:
    value: 300
mixed_precision:
    value: bf16
num_generations:
    value: 12
num_latent_t:
    value: 1
output_dir:
    value: /root/autodl-tmp/DiffusionGRPO/data/outputs/grpo
precondition_outputs:
    value: false
pretrained_model_name_or_path:
    value: /root/autodl-tmp/.cache/hub/models--black-forest-labs--FLUX.1-dev/snapshots/3de623fc3c33e44ffbe2bad470d0f45bccf2eb21
resume_from_checkpoint:
    value: null
sampler_seed:
    value: 1223627
sampling_steps:
    value: 20
seed:
    value: 42
selective_checkpointing:
    value: 1
shift:
    value: 3
sp_size:
    value: 1
t:
    value: 1
timestep_fraction:
    value: 0.6
train_batch_size:
    value: 2
train_sp_batch_size:
    value: 2
use_aesthetics_reward:
    value: true
use_cpu_offload:
    value: false
use_ctr_reward:
    value: false
use_ecp_reward:
    value: false
use_group:
    value: true
use_hpsv2:
    value: true
use_pickscore:
    value: false
use_t2i_align_reward:
    value: false
vae_model_path:
    value: /root/autodl-tmp/.cache/hub/models--black-forest-labs--FLUX.1-dev/snapshots/3de623fc3c33e44ffbe2bad470d0f45bccf2eb21
w:
    value: 1024
weight_decay:
    value: 0.0001
